
name: w1+w2

on:
  workflow_dispatch:

jobs:
  w1:
    uses: hypnotoadhq/test_github_actions/.github/workflows/w1.yml@main

  w2:
    uses: hypnotoadhq/test_github_actions/.github/workflows/w2.yml@main
