
name: w1+w2

on:
  workflow_dispatch:

jobs:
  w1:
    uses: hypnotoadhq/test_github_actions/blob/main/.github/workflows/reusable/w1.yml@main

  w2:
    uses: hypnotoadhq/test_github_actions/blob/main/.github/workflows/reusable/w2.yml@main
